// Generated by CoffeeScript 1.6.2
(function() {
  var Event;

  Event = (function() {
    function Event(type) {
      this.type = type;
      this.emmiter = null;
    }

    return Event;

  })();

}).call(this);
